# Generated by Django 3.2.6 on 2021-08-19 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("link", models.URLField(verbose_name="Link")),
                (
                    "creation_date",
                    models.DateField(
                        default=datetime.date(2021, 8, 19), verbose_name="Creation Date"
                    ),
                ),
                ("votes", models.IntegerField(default=0, verbose_name="Votes")),
                (
                    "author_name",
                    models.CharField(max_length=50, verbose_name="Author Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_name_comment",
                    models.CharField(max_length=50, verbose_name="Author Name"),
                ),
                ("content", models.TextField(max_length=150, verbose_name="Content")),
                (
                    "creation_date_comment",
                    models.DateField(
                        default=datetime.date(2021, 8, 19), verbose_name="Creation Date"
                    ),
                ),
                (
                    "post_comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="newsboard.post"
                    ),
                ),
            ],
        ),
    ]
