# Generated by Django 3.2.6 on 2021-08-20 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newsboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="creation_date_comment",
            field=models.DateField(
                default=datetime.date(2021, 8, 20), verbose_name="Creation Date"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post_comment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comment",
                to="newsboard.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="creation_date",
            field=models.DateField(
                default=datetime.date(2021, 8, 20), verbose_name="Creation Date"
            ),
        ),
    ]
